apiVersion: apps/v1
kind: Deployment
metadata:
  # uniq in namespace
  name: a9-site
  #labels:
  # app: site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      name: app-pod
      labels:
        app: site
    spec:
      containers:
        - name: app-container
          image: raknjarasoa/a9-site
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m